### ISSUE TITLE
Unable to connect to devices on macOS

### ISSUE THREAD

**Issue by landon-chaos** [NordicSemiconductor/IOS-nRF-Connect#104]
I'm using a MacBook Pro with the M1 Pro chip, and I've downloaded the iOS version of Nordic Connect. While the app is available on the Mac App Store, it appears as though there's an issue connecting to devices when running on Mac.

**Comment by dinesharjani** [comment]
You are correct. We've made changes to make nRF Connect work better on Macs but that code is not being executed since the app thinks it's on iOS.

We have builds for the Mac in Beta. If you provide me with an email, I will do my best to add you tomorrow and once the latest version goes through TestFlight you should have it available to use on your Mac, both on Intel and Apple Silicon.
