### ISSUE TITLE
Device reports unknown error

### ISSUE THREAD

**Issue by DG12** [NordicSemiconductor/IOS-nRF-Connect#119]
Your device reports an unknown error for Bluetooth use. 

Adding error code to message might be helpful. 

Tapping anywhere has no response. 
Must kill app. No change to any setting. 
Restart now ok.

**Comment by dinesharjani** [comment]
Can you provide a screenshot?

**Comment by DG12** [comment]
Would you prefer feedback email to you?  
to [mag@NordicSemi.com](mailto:mag@NordicSemi.com)?  or github issue?

**Comment by dinesharjani** [comment]
Email or this issue works. I'd just like to get some more context because otherwise I don't know where to look for the issue - is Bluetooth disabled from Settings? Or from the Control Center? Are you using Peripheral Tab to Advertise or act as a BLE Server? Also, a screenshot would be helpful as mentioned.
