### ISSUE TITLE
Tabs at top of connected device menu don't populate

### ISSUE THREAD

**Issue by droidecahedron** [NordicSemiconductor/IOS-nRF-Connect#137]
iOS `16.6.1` (*Confirmed to also still be present in iOS `17.1.1`*)
App version `2.7 `

Requires a swipe right to see the client server log tabs etc.

<img src="https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/63935881/5f7616cf-1a27-4207-8a76-334418a9507e" width="200" />
<img src="https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/63935881/a5397938-efe6-4eba-b01b-990df4abbbf6"  width="200" />

Left: Pre-swipe (no tabs populated), right: post-swipe (tabs now populated)

Additionally, with a stock peripheral uart application v2.5: 
the uart TX characteristic is not updating on the client screen anymore. Worked fine in previous version. 
I tested a lbs application and it worked fine on the new app. I have another mobile device on ios `15.4.1` and application `2.5.3` and the notifications work as expected for peripheral uart. If this requires a separate ticket, feel free to let me know.

**Comment by dinesharjani** [comment]
Yup, @droidecahedron we're aware ^^ Another user told us about this. We quickly submitted a fix in the form of version 2.7.1, but it's stuck in review due to Thanksgiving holidays. I hope they get back at it tomorrow. We're also working on a follow-up 2.7.2 with more fixes.

Going to mark this as closed for now, even though the fix is not available right now. But it should be soon.
