### ISSUE TITLE
Unable to load Firmware to begin update when using file on OneDrive

### ISSUE THREAD

**Issue by markb-EE** [NordicSemiconductor/IOS-nRF-Connect#140]
When I try to use a file from Microsoft OneDrive I get the following error:

![image](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/8332189/47b3e609-81b1-4252-9838-a7e352a7a45e)

Steps:
* Add OneDrive app from Apple App Store to iPhone
* Upload a DFU .zip image to OneDrive account
* Open nRF Connect for iOS
* Connect to a device with DFU Service running
* Press the "Open Document Picker" button
* Browse to top level using the "< Back"/"< Browse" buttons
* Select the OneDrive location (see image below)
* Select DFU .zip image
* Screen with error above is displayed

![image](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/8332189/fa22830d-f2b5-4dd3-988f-86d882bfda84)

**Comment by ChaunceyLong** [comment]
This happened to me too, how did you solve it?

**Comment by dinesharjani** [comment]
Very dumb question - (sorry for the delay since I'm vacation until next week) - do you know the .ZIP file is a valid file for DFU?

Otherwise, it could be a parsing error, or an issue reading the file specifically from OneDrive. You can also import the file into nRF Connect by connecting the iPhone to the Mac and dragging it into nRF Connect from the Finder. You can also try to read the file from iCloud Drive.

**Comment by markb-EE** [comment]
The .zip file is valid. I’m able to us it for DFU if I import it to nRF
connect. I did this by using the “Open in Another App” option in One Drive
and selecting nRF Connect:



This has been a long standing issue, I only just got around to reporting it.

**Comment by dinesharjani** [comment]
Disregard my previous comment, I'm able to reproduce the issue using OneDrive as you mentioned.

**Comment by dinesharjani** [comment]
Alright, I believe I have this fixed. It will ship with 2.7.3 as well.
