### ISSUE TITLE
Delete DFU Packages

### ISSUE THREAD

**Issue by GoodnatureBeacon** [NordicSemiconductor/IOS-nRF-Connect#20]
I'm using the DFU functionality of nRF Connect and it would be really good to be able to delete old packages.

**Comment by jovirus** [comment]
Hi @GoodnatureBeacon You can swipe left to delete firmwares.

**Comment by GoodnatureBeacon** [comment]
I meant under the "Distribution Packet (Zip)" Menu not the "My Firmwares" menu. Packages get added to this when you send them to nRF Connect, but there is no way of deleting them

**Comment by mostafaberg** [comment]
@GoodnatureBeacon Sorry about this mistake, I can confirm it's a bug on our side and will be fixed in the next release, problem is there's an invisible view that's over the approximate location of the third raw, causing it to block touches. to overcome that, you may try delete the firmware abote it first to move it away from the invisible view's location.

**Comment by GoodnatureBeacon** [comment]
Just for reference, this is a seperate issue to the Third Item issue. This issue refers to not being able to delete Firmwares under the "Distribution Packet (Zip)" menu, not the "My Firmwares" menu where this was an issue.

**Comment by mostafaberg** [comment]
@GoodnatureBeacon of course!, i missed that point, will reopen the other issue again

**Comment by jovirus** [comment]
fix in V1.8.5
