### ISSUE TITLE
log verbose yellow is illegible and time display in ms

### ISSUE THREAD

**Issue by DG12** [NordicSemiconductor/IOS-nRF-Connect#4]
Please revise the log to use a different color for verbose than yellow(gold?)

It would be helpful to have the second and subsequent lines for each event to start under the time (not indented ) allowing more viewable data on the screen,

A nice  idea might be an option to show time in  milliseconds since connect or milliseconds since last entry.

Thank you

**Comment by jovirus** [comment]
Hi @DG12 Thank you for suggestions, what is the motivation of using other colours than yellow? 
I think the alignment of the log text are looking good, since it give a intuitive way of displaying time sequences and respective message. 
The format of time [HH:MM:SS:**mmm**] 
The last three digits is in millisecond

**Comment by DG12** [comment]
re yellow: contrast is very bad and cannot be read.

**Comment by jovirus** [comment]
Thank you for suggestions
