### ISSUE TITLE
Cannot add DFU files

### ISSUE THREAD

**Issue by 0ge** [NordicSemiconductor/IOS-nRF-Connect#49]
I'm trying to add the zip-file generated by following [this tutorial](https://devzone.nordicsemi.com/b/blog/posts/getting-started-with-nordics-secure-dfu-bootloader). However, when I follow the instructions in the iOS app, once I share the file with the app, it just starts the app. No files are added. Same for hex and zip files.

And if I try to add the files when the app is already started, it jumps back to the scanner tab. However, it appears to have another scanner tab active in the background, because no peripherals appear in the new view.

**Comment by SwissKnife** [comment]
This issue is still present in nRF Connect Version 2.0.1, Built Number 55, on iPhone with iOS 12.4.1.
After using the option "save to nRF connect" from "mail" to save a valid DFU ZIP archive has no result. nRF Connect ist poping up, but on the settings page. The Inbox is empty.
I have to copy the file to my "iCloud Drive" and select it manually using the "Document Picker".
Fix the "save to nRF Connect" or remove it from the system.
