### ISSUE TITLE
Share does not work IPad

### ISSUE THREAD

**Issue by johannesbrunner-wd** [NordicSemiconductor/IOS-nRF-Connect#82]
If I click on the share button the applications to share with are quickly shown and immediately closed afterwards just before it is possible for somebody to select an application to share.

Also the send feedback button is not working.

IPadOS Version 14.1 (18A8395)
IPad is 6th Generation

Application Version is 2.3.2

**Comment by dinesharjani** [comment]
Hi @johannesbrunner-wd ,

We have observed the behaviour you're describing. Unfortunately, it's code outside of our control, because we just ask iOS to share some content and it pops up and disappears again. We devoted some time to provide some workarounds to it, but it wasn't easy to trick iOS into behaving well.

We will do our best to give this another look. Thank you.
